### ISSUE TITLE
Fix `sh -c` whe using `pass` option

### ISSUE THREAD

**Issue by micalevisk** [fifsky/ssh-action#12]
If my password chars like `)` I'll get this error: `sh: syntax error: unexpected ")"` due to the line below
https://github.com/fifsky/ssh-action/blob/9c01abf173725894171172a883251f494b60ffe0/entrypoint.sh#L34

I think you should change this to:

```bash
sh -c "sshpass -p \"$INPUT_PASS\" ssh $INPUT_ARGS -o StrictHostKeyChecking=no -p $INPUT_PORT ${INPUT_USER}@${INPUT_HOST} < $HOME/shell.sh" 
```
or
```bash
sh -c 'sshpass -p "$INPUT_PASS" ssh $INPUT_ARGS -o StrictHostKeyChecking=no -p $INPUT_PORT ${INPUT_USER}@${INPUT_HOST} < $HOME/shell.sh'
```

**Comment by fifsky** [comment]
Yes, you are right
