### ISSUE TITLE
Question : generate a file

### ISSUE THREAD

**Issue by bryxfr** [fifsky/ssh-action#15]
Hi

How can I use your tool to generate an environment file for my Symfony project? I have a file with ${{ secrets.MySQL }} for example to ensure the connection and not to give the developers the identifiers for security reasons. Does the vi or nano command work? If so, how can I use them, I'm not very good at command line in SSH.

Thanks ;)

**Comment by fifsky** [comment]
You can refer to this
https://github.com/fifsky/blog/blob/master/.github/workflows/publish.yml#L52

You may need to base64 encode your data first
