### ISSUE TITLE
shell script is stuck in infinite loop

### ISSUE THREAD

**Issue by koradiyakaushal** [fifsky/ssh-action#16]
workflow file:
name: Development
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login Via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su
            cd /var/www/html/
            sh -x dev.sh
            echo "ssh run finished"
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY}}
          args: "-tt -vvv"

dev.sh file

#! /bin/sh
git add .
echo "Reseting the dev branch:"
git reset --hard
echo "Pulling the dev branch:"
git pull
npm install
npm run build
pm2 restart server.js
date

all of the above shell commands run perfectly but it's get stuck forever.

![image](https://user-images.githubusercontent.com/36811899/115138316-e6667400-a01a-11eb-81e8-f005aebd3584.png)
(last message in build logs)

**Comment by fifsky** [comment]
Maybe you can try it
```
sh -x dev.sh &
```

**Comment by ivangonzalezg** [comment]
> Maybe you can try it
> 
> ```
> sh -x dev.sh &
> ```

Is there any way to see the log?

**Comment by ivangonzalezg** [comment]
> Maybe you can try it
> 
> ```
> sh -x dev.sh &
> ```

@fifsky 
Is there a way to know if the execution was successful or to see the log?

**Comment by fifsky** [comment]
@ivangonzalezg

**Comment by fifsky** [comment]
@ivangonzalezg 
if shell execution was abnormal exit,GitHub action steps will fail

for example
https://github.com/fifsky/ssh-action/runs/2970546344?check_suite_focus=true

**Comment by ivangonzalezg** [comment]
First of all, thanks for your reply

I know what you mean. But it seems that the command runs in the background and doesn't wait for the result and if there are any errors in the execution I have no way of knowing

This is my configuration

```yml
steps:
      - uses: actions/checkout@v2
      - name: Deploying WEB
        uses: fifsky/ssh-action@master
        with:
          command: |
            sh -x ./update-web.sh &
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}
          args: "-tt -vvv"
```
```bash
# update-web.sh
#!/bin/bash

echo "Stoping WEB service"
sudo service WEB stop
cd /home/ubuntu/web
echo "Getting changes"
git pull
echo "Instaling dependencies"
yarn
echo "Building..."
yarn build
echo "Starting WEB service"
sudo service WEB start
echo "WEB service updated"
```

And this is the result


```bash
debug2: channel 0: input drain -> closed
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jul  2 07:31:21 UTC 2021

  System load:  0.0                Processes:             116
  Usage of /:   20.3% of 29.02GB   Users logged in:       1
  Memory usage: 47%                IPv4 address for eth0: 0.0.0.0
  Swap usage:   0%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

44 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


Last login: Fri Jul  2 06:09:56 2021 from 0.0.0.0

ubuntu@ip-172-31-32-94:~$ sh -x ./update-web &
[1] 1844
ubuntu@ip-172-31-32-94:~$ 
ubuntu@ip-172-31-32-94:~$ exit
logout
debug3: receive packet: type 98
```
