### ISSUE TITLE
Takes at least 3 minutes to execute a script that takes less than 20 seconds to finish

### ISSUE THREAD

**Issue by lifehackerhansol** [fifsky/ssh-action#25]
This may be me not knowing how this is supposed to work, but a list of commands that should be done in at least 15 seconds takes 3 minutes to finish. When monitoring the logs while the action is running, it appeared that the entire list of commands actually finished but didn't actually recognize as finished until at least 3 minutes (running one right now, it's going over that.)

Is there any way to make the ssh-action recognize that it's completed?

See this workflow here: https://github.com/DS-Homebrew/TWLHelper/runs/3349202507

**Comment by lifehackerhansol** [comment]
It seems this is super varied as well. The latest commit is now at 9 minutes.

Maybe a feature request is to detect whether the SSH has exited? So one can detect that the portion is complete.

**Comment by fifsky** [comment]
I'm sorry. I don't know. What's the problem, Maybe you can try it
```
git pull --force
```
Or print the current time at the start and end
```
echo `date`
```

**Comment by lifehackerhansol** [comment]
I found that the command `nohup` is causing ssh to stay active.

The script is as follows:
```sh
#!/bin/bash

echo Rebooting bot...
cd TWLHelper
git pull
kill -9 $(cat twlhelper.pid)
pip install -r requirements.txt
nohup ./twlhelper.py 1>/dev/null 2&>1 & echo $! > twlhelper.pid
sleep 3
echo Success.
```

nohup continues to stay connected to stdout which keeps the script locked in (and can't exit for some reason either.) Sending nohup stdout into /dev/null fixes this. 

I'm not sure if that is something fixable or not. So I'll leave the issue open for the time being.
