### ISSUE TITLE
输入重定向 <

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [fifsky/ssh-action#28]
sh -c "ssh $INPUT_ARGS -i $KEYFILE -o StrictHostKeyChecking=no -p $INPUT_PORT ${INPUT_USER}@${INPUT_HOST} < $HOME/shell.sh" 
这句话是什么意思呢？可以看下$HOME/shell.sh里的内容吗

**Comment by fifsky** [comment]
See  https://github.com/fifsky/ssh-action/blob/master/entrypoint.sh#L31-L32
