### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by elijaholmos** [fifsky/ssh-action#29]
Hello, I recently went to run the action, and I received a build failure. View the attached screenshot:
![image](https://user-images.githubusercontent.com/35435704/146842952-792f242a-6d44-4d01-89b8-6e8d20a31f0a.png)

The repo is public and you can view the full log information at: https://github.com/Leyline-gg/leyline-discord/runs/4588464171?check_suite_focus=true

Let me know if there's any other information I can provide or actions I can take on my end to resolve this error. Thanks.

**Comment by fifsky** [comment]
Is docker API timeout, you can try again

This is the test I just did
https://github.com/fifsky/ssh-action/runs/4589865480?check_suite_focus=true

**Comment by elijaholmos** [comment]
thanks for the quick response, just confirmed it works on my end 👍
