### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Albinzr** [fifsky/ssh-action#5]
Run fifsky/ssh-action@master
/usr/bin/docker run --name ee6a231e3f8c5e44f458716def90b89c022_b6d12a --label 671ee6 --workdir /github/workspace --rm -e INPUT_COMMAND -e INPUT_HOST -e INPUT_USER -e INPUT_KEY -e INPUT_PORT -e INPUT_PASS -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/Applytics_Core/Applytics_Core":"/github/workspace" 671ee6:a231e3f8c5e44f458716def90b89c022
 Warning: This action does not currently support host verification; verification is disabled. 
 
Pseudo-terminal will not be allocated because stdin is not a terminal.
cd /tmp
ls -a
 exit
Start Run Command
Warning: Permanently added '***' (ECDSA) to the list of known hosts.
root@***: Permission denied (publickey).
##[error]Docker run failed with exit code 255

 - name: deploy
      uses: fifsky/ssh-action@master
      with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}

**Comment by arys** [comment]
Hello @Albinzr how did you solve this problem?

**Comment by fifsky** [comment]
@arys777  

File permission issues that are normally key must be set to 600
