### ISSUE TITLE
***@***: Permission denied (publickey).

### ISSUE THREAD

**Issue by knynkwl** [fifsky/ssh-action#7]
Does the `key` need to be the contents of the `~/.ssh/id_rsa.pub` on your local machine?

```
Load key "/github/home/.ssh/deploy_key": invalid format
***@***: Permission denied (publickey)

**Comment by knynkwl** [comment]
```
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.FORGE_HOST }}
        user: ${{ secrets.FORGE_USERNAME }}
        port: 22
        key: "${{ secrets.SSH_PRIVATE_KEY}}"
        command: |
          ls -a

**Comment by fifsky** [comment]
key is private  `~/.ssh/id_rsa`

**Comment by YakovL** [comment]
Could you please explain what exactly were you doing wrong and how did you fix it? I'm trying to use private key (from `~/.ssh/id_rsa`) as a secret passed to `key`, but I do get the

> ***@***: Permission denied (publickey).

error message

**Comment by leonidlewis** [comment]
Same error here.
