### ISSUE TITLE
Error: Load key "/github/home/.ssh/deploy_key": invalid format

### ISSUE THREAD

**Issue by rickserrat** [fifsky/ssh-action#8]
Hi.
On my server I generated a key with ssh-keygen, copied the private key (id_rsa) and inserted it into the repository's secrets.
I'm using the example: https://github.com/fifsky/ssh-action/blob/master/.github/workflows/test.yml
replace only $ {{secrets.HOST}} with '134.23.xx.xxx'.

debug:

```
OpenSSH_8.3p1, OpenSSL 1.1.1g 21 Apr 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname 134.23.xx.xxx is address
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug2: ssh_connect_direct
debug1: Connecting to 134.23.xx.xxx [134.23.xx.xxx] port 22.
debug1: Connection established.
load pubkey "/github/home/.ssh/deploy_key": invalid format
```

What am I doing wrong?

**Comment by fifsky** [comment]
Maybe you need to check the key format

This might help you: https://github.com/Pendect/action-rsyncer/issues/2

Or get the key like this

```
cat ~/.ssh/id_rsa
```

**Comment by rickserrat** [comment]
Thanks.
